const Respuestas = [
  "Muy Homosexual... Sin ofender",
  "Muy Heterosexual... Sin ofender",
  "Gay... Sin ofender",
  "Sí.",
  "No.",
  "Tal vez.",
  "Es posible.",
  "Definitivamente sí.",
  "Definitivamente no.",
  "No lo creo.",
  "Claro que sí.",
  "Por supuesto.",
  "No cabe duda.",
  "Sin duda.",
  "No cuentes con ello.",
  "No te ilusiones.",
  "Mejor no te lo digo ahora.",
  "Concentra y pregunta de nuevo.",
  "No puedo predecirlo ahora.",
  "Es confuso, intenta de nuevo.",
  "Pregunta después.",
  "No estoy seguro.",
  "Las señales apuntan a sí.",
  "Las señales apuntan a no.",
  "No lo veo probable.",
  "Es poco probable.",
  "No estoy convencido.",
  "Es cuestionable.",
  "Respuesta incierta.",
  "Sí, pero con condiciones.",
  "No, a menos que cambies algo.",
  "Las perspectivas son buenas.",
  "Las perspectivas son sombrías.",
  "No lo veo en el futuro cercano.",
  "No puedo responder eso en este momento.",
  "Está en tus manos.",
  "Toma una decisión informada.",
  "Considera tus opciones.",
  "Confía en tu instinto.",
  "No me hagas elegir.",
  "Prefiero no decirlo.",
  "Mantén la calma y espera.",
  "No te precipites.",
  "No hagas suposiciones.",
  "Podría ser un desafío.",
  "Piénsalo detenidamente.",
  "Puede que necesites ayuda.",
  "No lo sabré hasta que lo intentes.",
  "No te rindas.",
  "Mantén una actitud positiva.",
  "Busca consejo.",
  "Escucha a tu corazón.",
  "Explora todas las posibilidades.",
  "No dejes que el miedo te detenga.",
  "Enfócate en tus metas.",
  "Sé paciente.",
  "No te conformes fácilmente.",
  "Aprende de tus errores.",
  "Mantén la cabeza en alto.",
  "No tengas miedo de cambiar.",
  "Rodéate de personas positivas.",
  "Sé valiente en tus decisiones.",
  "No permitas que otros te influyan demasiado.",
  "La suerte está de tu lado.",
  "Debes esforzarte más.",
  "No te preocupes por eso.",
  "Concéntrate en el presente.",
  "Planifica con cuidado.",
  "No dejes que los obstáculos te detengan.",
  "Aprovecha las oportunidades.",
  "No te detengas ante la adversidad.",
  "Confía en tu intuición.",
  "Mantén tus expectativas realistas.",
  "No te precipites en conclusiones.",
  "Busca el equilibrio en todo.",
  "La paciencia dará sus frutos.",
  "Aprende de experiencias pasadas.",
  "No te preocupes por lo que no puedes controlar.",
  "Mantén la mente abierta.",
  "Evita tomar decisiones impulsivas.",
  "Enfrenta tus miedos.",
  "No subestimes tu capacidad.",
  "No permitas que los demás te desalienten.",
  "Hazlo por ti mismo/a, no por los demás.",
  "Enfócate en el camino a largo plazo.",
  "No olvides cuidarte a ti mismo/a.",
  "No te tomes todo demasiado en serio.",
  "Aprende a adaptarte.",
  "La autodisciplina es clave.",
  "Mantén tus metas en mente.",
  "Cree en tu voz interior.",
  "La perseverancia es esencial.",
  "Mantén la mente positiva.",
  "Acepta los cambios con gracia.",
  "No temas pedir ayuda.",
  "Rodéate de amor y apoyo.",
  "Sé agradecido/a por lo que tienes.",
  "Enfrenta los desafíos con determinación.",
  "Abraza nuevas oportunidades.",
  "No te desanimes por los contratiempos.",
  "Aprende a dejar ir lo que ya no te sirve.",
  "Hazlo con pasión o no lo hagas en absoluto.",
  "Tú tienes el poder de decidir.",
];
module.exports = () =>
  Respuestas[Math.floor(Math.random() * Respuestas.length)];
